services:
  app:
    build: 
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ~/.ssh:/opt/meesa/.ssh
      - ../.devcontainer/zshrc:/opt/meesa/.zshrc
      - ..:/opt/meesa/code
    command: ["tail -f /dev/null"]

  db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db
    networks:
      - my-website

